### ISSUE TITLE
Better handling of network exceptions

### ISSUE THREAD

**Issue by Brycey92** [AuraDevelopmentTeam/AuraUpdateChecker#3]
#### Issue Description:
Every so often, my console is spammed with timeout errors where Aura couldn't contact Ore or couldn't load a plugin's page on Ore. See #2 for the beginning of the discussion on this.

#### What happens:
When printing the exception's message, Aura is also printing its stack trace, which in this case (and probably most network exceptions) is unnecessary.

#### What you expected to happen:
The stack traces could be printed to debug output, and only the actual message like "Socket timed out" could be printed as a warning. Timeouts could also stand to get some proper handling, according to @BrainStone.

____
#### Affected Versions :

- Minecraft: 1.12.2
- AuraUpdateChecker: 1.1.2.167

**Comment by BrainStone** [comment]
Mind to give me some logs how it looks currently? I’m not sure how to reproduce those network errors.

**Comment by BrainStone** [comment]
Here you go:
https://ore.spongepowered.org/AuraDevelopmentTeam/Aura-Update-Checker/versions/1.1.3.176

**Comment by Brycey92** [comment]
Thanks! Sorry I didn't get those logs to you. I became busy with other things and forgot you had asked for them. I'll give it a test eventually when I have more free time.

**Comment by BrainStone** [comment]
Cheers on the fast responses and feedback. I'll be happy to implement more feature requests and fix bug reports by you ^^
