### ISSUE TITLE
Unable to connect to the ore repository.

### ISSUE THREAD

**Issue by CJYKK** [AuraDevelopmentTeam/AuraUpdateChecker#5]
(Using translation)
#### What happens:
No matter how many times the server is restarted, it always prompts "Could not contact the Ore Repository API for plugin XXX".
(I also added the translation of zh_CN, I don’t know where to submit.)

#### What you expected to happen:
Check for updates normally.

#### Steps to reproduce:

1.Copy the plugin to the mods folder
2.Start the server
3.Report an error

____
#### Affected Versions :

- Minecraft: 1.12.2
- AuraUpdateChecker:AuraUpdateChecker-1.1.3.176
- Sponge:spongevanilla-1.12.2-7.1.9
- Other related mods:

[latest.log](https://github.com/AuraDevelopmentTeam/AuraUpdateChecker/files/5589934/latest.log)

```

**Comment by BrainStone** [comment]
Interesting. While the plugin is indeed broken because the API got turned off I believe the error is happening because the domain is blocked in your country.

I'll try to get a fix ready.

Anyways you can just create a pull request for the translation.

**Comment by CJYKK** [comment]
(Using translation)
I still don't know how to operate, I uploaded the translation file as an attachment.
Thank you!
(Change file type)
[zh_CN.lang.txt](https://github.com/AuraDevelopmentTeam/AuraUpdateChecker/files/5596850/zh_CN.lang.txt)

**Comment by BrainStone** [comment]
I found a guide on how to make a Pull Request: https://docs.github.com/cn/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

No idea how good it is. It's available in other languages as well.

**Comment by BrainStone** [comment]
Try this file, Should be working now:

https://maven.aura-dev.team/repository/auradev-snapshots/dev/aura/updatechecker/AuraUpdateChecker/1.1.4.188-DEV/AuraUpdateChecker-1.1.4.188-DEV.jar

**Comment by BrainStone** [comment]
I added your translation. Thank you very much

**Comment by CJYKK** [comment]
No, it's not working!

**Comment by BrainStone** [comment]
It’s working for me which leads me to believe the website is being blocked by your government.

**Comment by CJYKK** [comment]
![My VPN](https://user-images.githubusercontent.com/59359590/102075762-b2e3c500-3e41-11eb-91fd-680ef9a356f1.png)
![spongevanilla-1 12 2-7 3 0](https://user-images.githubusercontent.com/59359590/102075769-b4ad8880-3e41-11eb-96b5-92b07619ef49.png)
![spongevanilla-1 12 2-7 1 9](https://user-images.githubusercontent.com/59359590/102075772-b5deb580-3e41-11eb-9aec-d4c39a177fa7.png)
report errors.

**Comment by CJYKK** [comment]
![My VPN](https://user-images.githubusercontent.com/59359590/102075837-d3138400-3e41-11eb-8b52-62bc4ae0b68c.png)
My VPN.
![spongevanilla-1 12 2-7 1 9](https://user-images.githubusercontent.com/59359590/102075882-e0307300-3e41-11eb-8a3a-82f8b47f996a.png)
SpongeVanilla-1 12 2-7 1 9.
![spongevanilla-1 12 2-7 3 0](https://user-images.githubusercontent.com/59359590/102076023-0eae4e00-3e42-11eb-8a4c-5a9213aa0262.png)
Spongevanilla-1.12.2-7.3.0.

**Comment by BrainStone** [comment]
My apologies. You did get in fact a not working version.

Use this: https://maven.aura-dev.team/repository/auradev-snapshots/dev/aura/updatechecker/AuraUpdateChecker/1.1.4.208-DEV/AuraUpdateChecker-1.1.4.208-DEV.jar

**Comment by CJYKK** [comment]
I know it's annoying!
![屏幕截图 2020-12-15 182205](https://user-images.githubusercontent.com/59359590/102202567-74620f00-3f02-11eb-8f8b-f1f01d3dfe2a.png)
SpongeVanilla-1.12.2-7.3.0.

Do I have any pre plugins not installed?

**Comment by BrainStone** [comment]
No. This looks like a conflict with another plugin. 

Please make sure it works with only this plugin installed. 

If it does you need to remove the other plugins one by one until you found the one that causes issues. See if there is an update for it. If not reach out to the plugin author and ask them to update bStats.
